/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package practice;
//import java.io.*;
import org.junit.Test;
import static org.junit.Assert.*;
public class AppTest {
    public static String choice;
    @Test 
    public void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test 
    public void appHasSetGreeting() { //gtest if greeting was done. AssertEquals does that
        App classUnderTest = new App();
        //String expected;
        classUnderTest.setGreeting( "What's up!" );
        assertEquals("app should have a greeting", "What's up!", 
        classUnderTest.getGreeting());
    }
    @Test 
    public void rightAnimalPicked() {
        App animal = new App();
        //commented part didn't quite go to plan, if i have more time, i'll try to figuer it out.
        //it's mean to involve commmuniation between main and test methods with user input for question: cats or dogs?
       /*ByteArrayInputStream bais = new ByteArrayInputStream(); 
        String right = "dogs";
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        PrintStream printStream = new PrintStream(baos);
        System.setOut(printStream);
        System.setIn(bais);

        AppTest.main(null);
        String ans = baos.toString();*/

        System.out.println("Cats or dogs?");
        
        animal.catsVsDogsAsk("dog"); //(ans);
        try{
            assertEquals("dogs", animal.getAnimal());
            System.out.println("good choice");}
        catch(org.junit.ComparisonFailure error){
            System.out.println("you heathen");
        }
    
    }

    /*public static void main(String[] args) {

        Scanner scanner = new Scanner(System.in);
        System.out.println("Cats or dogs?");
        String ans = scanner.nextLine();
        System.out.println(ans);

    }*/

}
